// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```'

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Oqcxs54J3ELVtQ7KdPCeHTBhNJw7C_0',
    appId: '1:971149297377:web:0824688884b1ace8f999a0',
    messagingSenderId: '971149297377',
    projectId: 'buyngo-db933',
    authDomain: 'buyngo-db933.firebaseapp.com',
    storageBucket: 'buyngo-db933.firebasestorage.app',
    measurementId: 'G-HC4PR0RQJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfWXva8ALLwdDXBF2OXWVTQtTg2wbful8',
    appId: '1:971149297377:android:8f744c612304d76bf999a0',
    messagingSenderId: '971149297377',
    projectId: 'buyngo-db933',
    storageBucket: 'buyngo-db933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWdIC9SLKUYFM-rVBslUo4FwCH2rL0WDs',
    appId: '1:971149297377:ios:74b8d92f93967f8cf999a0',
    messagingSenderId: '971149297377',
    projectId: 'buyngo-db933',
    storageBucket: 'buyngo-db933.firebasestorage.app',
    iosBundleId: 'com.example.pppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWdIC9SLKUYFM-rVBslUo4FwCH2rL0WDs',
    appId: '1:971149297377:ios:74b8d92f93967f8cf999a0',
    messagingSenderId: '971149297377',
    projectId: 'buyngo-db933',
    storageBucket: 'buyngo-db933.firebasestorage.app',
    iosBundleId: 'com.example.pppp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Oqcxs54J3ELVtQ7KdPCeHTBhNJw7C_0',
    appId: '1:971149297377:web:91ff5b65aa7032b9f999a0',
    messagingSenderId: '971149297377',
    projectId: 'buyngo-db933',
    authDomain: 'buyngo-db933.firebaseapp.com',
    storageBucket: 'buyngo-db933.firebasestorage.app',
    measurementId: 'G-MYQJ869PF0',
  );
}

